const expree=require('express')
const router=expree.Router()
const authRouter=require('./auth')
const ProductRouter=require('./productRoutes')
const CartRouter=require('./cartRoutes')
const OderRouter=require('./oderRoutes')
const AuthAdminRouter=require('./authAdmin')
const ProductAdminRouter=require('./productAdmin')
const CategoryRoutes=require('./categoryAdmin')
router.use("/auth",authRouter)
router.use("/api",ProductRouter)
router.use("/api",CartRouter)
router.use("/api",OderRouter)
router.use("/api",AuthAdminRouter)
router.use("/api",ProductAdminRouter)
router.use("/api",CategoryRoutes)
module.exports=router